### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by filerun** [teonsystems/php-text-extraction#1]
Hi,

Thanks for a great library!

I have the following two suggestions for you:
1. Remove the "Teon\Base" dependency, as it only adds weight to the library, while the only used two-line function is "\Teon\Base\Stdlib\ClassUtils::getBaseClassName()".
2. Update the folder structure so that applications can load the library without Composer but just based on PSR-4

P.S. I am testing the library out and if it meets my requirements, I will most probably contribute some extractors soon.

Regards,

Vlad

**Comment by bostjan** [comment]
Excellent.

Unfortunately development on this one stalled a bit, but having a bit of bump helps nicely from time to time :)

Pull requests welcome, for the two suggestions from your message too.

Q1: It makes sense, Base is rather large and - well, clumsy is the word I am looking for:)\\

Q2: What structure do you suggest?

b.

**Comment by filerun** [comment]
Sorry for the late reply. In the end I went with Apache Tika for the text extraction in my project.

**Comment by bostjan** [comment]
Tika is great, indeed. Especially if you can afford to use a dedicated container for its deployment.
